### ISSUE TITLE
linux-kernel-broadwell-xps13: unused patches

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Dev/linux-kernel-extra#1]
XPS13 really dont need that much patches.
e.g.
Baytrail SDIO wireless patch

**Comment by bobcao3** [comment]
Also these following patches:
0026-bugfix-Surface-marvell-wifi-power-managem...
0023-driver-add-multitouch-support-for-Micros...
0022-driver-realtek-rtl8812au-rtl8821au.patch
0009-quirk-disable-i8042-check-on-apple-mac.patch

**Comment by Icenowy** [comment]
rtl8812au is a usb card.
I think XPS13 do have USB ports :-)
(In the realtek wireless card name scheme, the second letter is the port: e is pcie, u is usb, s is sdio, so please do not drop rtl?????u patches)
2016年9月3日 18:16于 Bob Cao notifications@github.com写道：Also these following patches:
0026-bugfix-Surface-marvell-wifi-power-managem...
0023-driver-add-multitouch-support-for-Micros...
0022-driver-realtek-rtl8812au-rtl8821au.patch
0009-quirk-disable-i8042-check-on-apple-mac.patch

**Comment by MingcongBai** [comment]
@bobcao3 Please go ahead with a PR.
